baseURL = 'http://example1.net/'
languageCode = 'ru-ru'
title = 'Example 1 NET'
theme = 'ananke'
enableGitInfo = true
timeZone = 'Local'
# Configuration Settings
# archetypeDir = 'archetypes'
# assetDir = 'assets'
# baseURL # hostname and path to the root
# build
# buildDrafts = false
# buildExpired = false
# buildFuture = false
# caches
# cascade
# canonifyURLs = false
# cleanDestinationDir = false
# contentDir = 'content'
# copyright = ''
# dataDir = 'data'
# defaultContentLanguage = 'en'
# defaultContentLanguageInSubdir = false
# disableAliases = false
# disableHugoGeneratorInject = false
# disableKinds = [] # [ 'page', 'home', 'section', 'taxonomy', 'term', 'RSS', 'sitemap', 'robotsTXT', '404' ]
# disableLiveReload = false
# disablePathToLower = false
# enableEmoji = false
# enableGitInfo = false
# enableInlineShortcodes = false
# enableMissingTranslationPlaceholders = false
# enableRobotsTXT = false
# frontmatter
# googleAnalytics = ''
# hasCJKLanguage = false # Chinese/Japanese/Korean languages
# ignoreFiles # [ '\.voo$', '\.boo$' ] use includeFiles excludeFiles mount options instead
# imaging
# languageCode = ''
# languages
# disableLanguages
# markup
# mediaTypes
# menus
# minify
# module
# newContentEditor = ''
# noChmod = false
# noTimes = false
# outputFormats
# paginate = 10
# paginatePath = 'page'
# permalinks
# pluralizeListTitles = true
# publishDir = 'public'
# related
# relativeURLs = false
# refLinksErrorLevel = 'ERROR'
# refLinksNotFoundURL
# removePathAccents = false
# rssLimit = -1
# sectionPagesMenu
# security
# sitemap
# summaryLength = 70
# taxonomies
# theme
# themesDir = 'themes'
# timesout = '30s'
# timeZone
# title
# titleCaseStyle = 'AP' # 'Chicago', 'Go'
# uglyURLs = false
# watch = false
#
# Configure Build
# [build] # Global build-related configuration options
#   useResourceCacheWhen # [ 'never' | 'always' | 'fallback' ] when yo use the cached resources in /resources/_gen for PostCSS and ToCSS
#   writeStats
#   noJSConfigInAssets
#
# Configure Server ( hugo server ) put in development environment
# [server]
# [[server.headers]]
#   for = '/**'
#   [server.headers.values]
#     Content-Security-Policy = 'script-src localhost:1313'
#     Referrer-Policy = 'strict-origin-when-cross-origin'
#     X-Content-Type-Options = 'nosniff'
#     X-Frame-Options = 'DENY'
#     X-XSS-Protection = '1; mode=block'
# [[server.redirects]]
#   force = false
#   from = '/myspa/**'
#   status = 200 # triggers a URL rewrite
#   to = '/myspa/'
#   from = '/**'
#   to = '/404.html'
#   status = 404
#
# Example Configuration
# baseURL = 'example.com'
# title = 'Example Site'
# [params]
#   AuthorName = 'Jon Doe'
#   ListOfFoo = ['foo1', 'foo2']
#   SidebarRecentLimit = 5
#   Subtitle = 'Example subtitle'
# [permalinks]
#   posts = '/:year/:month/:title'
#
# [frontmatter]
#   date = ['date', 'publishDate', 'lastmod']
#   # date = ['myDate', ':default']
#   expiryDate = ['expiryDate']
#   lastmod = [':git', 'lastmod', 'date', 'publishDate']
#   # lastmod = ['lastmod', ':fileModTime', ':default']
#   # first try to extract the value for .Lastmod, starting with the lastmod param
#   # then the content file's modification timestamp
#   # the last, :default should not be needed here, but Hugo will finally look for a valid date
#   # in :git, date, and then publishDate
#   publishDate = ['publishDate', 'date']
#   # aliases:
#   # - lastmod -modified
#   # - publishDate -pubdate
#   # - expiryDate -unpublishdate
# :default - shortcut to default settings
# :fileModTime - fetch date from content file's last modification timestamp
# :filename - fetch date from filename
# :git - git author date for the last revision of this content file (only if --enableGitInfo or enableGitInfo = true is set)
#
# [mediaTypes]
#
# [outputFormats]
#
# [minify]
# disableCSS = false
# disableHTML = false
# disableJS = false
# disableJSON = false
# disableSVG = false
# disableXML = false
# minifyOutput = false
# [minify.tdewolff]
# [minify.tdewolff.css]
# keepCSS2 = true
# precision = 0
# [minify.tdewolff.html]
# keepComments = false
# keepConditionalComments = true
# keepDefaultAttrVals = true
# keepDocumentTags = true
# keepEndTags = true
# keepQuotes = false
# keepWhitespace = false
# [minify.tdewolff.js]
# keepVarNames = false
# noNullishOperator = false
# precision = 0
# [minify.tdewolff.json]
# keepNumbers = false
# precision = 0
# [minify.tdewolff.svg]
# keepComments = false
# precision = 0
# [minify.tdewolff.xml]
# keepWhitespace = false
#
# [caches]
# [caches.assets]
# dir = ':resourceDir/_gen'
# maxAge = -1
# [caches.getcsv]
# dir = ':cacheDir/:project'
# maxAge = -1
# [caches.getjson]
# dir = ':cacheDir/:project'
# maxAge = -1
# [caches.getresource]
# dir = ':cacheDir/:project'
# maxAge = -1
# [caches.images]
# dir = ':resourceDir/_gen'
# maxAge = -1
# [caches.modules]
# dir = ':cacheDir/modules' # absolute path to directory where cache is stored
# maxAge = -1 # -1 - forever; 0 - cache off; "10s", "10m", "10h" - Go's time.Duration values
#   # :cacheDir - value of the cacheDir config option
#   # :project - current hugo project directory
#   # :resourceDir - value of the resourceDir config option
